apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: pick
  region: eu-central-1
  version: "1.27"
iam:
  withOIDC: true
nodeGroups:
  - name: default-nodegroup
    instanceType: t3.medium
    desiredCapacity: 5
    privateNetworking: true
addons:
- name: vpc-cni
  version: v1.17.1-eksbuild.1
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  configurationValues: |-
    enableNetworkPolicy: "true"
- name: coredns
  version: v1.10.1-eksbuild.7
- name: kube-proxy
  version: v1.27.10-eksbuild.2
- name: aws-ebs-csi-driver
  version: v1.28.0-eksbuild.1
  wellKnownPolicies:      
    ebsCSIController: true